server:
  port: 8761
spring:
  application:
    name: naming-server
eureka:
  instance:
    lease-renewal-interval-in-seconds: 0
  client:
    # Previne que o Eureka se auto-registre
    # Em produção deve-se retirar essa configuração
    register-with-eureka: true
    fetch-registry: true
